name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install dependencies
      run: |
        bundle
        sudo apt-get update
        # libxml2-utils: xmllint
        sudo apt-get install -y trang libxml2-utils xsltproc

    - name: Run tests
      run: rake test

    - name: Generate compact schema files
      run: |
        bundle exec rake schema.rnc schemaex.rnc

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: schema-files
        path: |
          schema.rnc
          schemaex.rnc
          schema.rng
          schemaex.rng
          docs/CHANGELOG.md
          docs/COPYING
          docs/README
          docs/UL-SN-DISCLAIMER
